import JSZip from 'jszip';
import type { Node, Edge } from '@xyflow/react';
import type { 
  EDOTNodeData, 
  CollectorNodeData, 
  FlowEdgeData,
  DeploymentModel,
  SDKNodeData
} from '../types';
import { generateCollectorYAML } from './yaml-generator';
import { generateDockerCompose } from './docker-compose-generator';
import { generateK8sManifests } from './k8s-manifest-generator';
import { generateSampleApp } from './sample-app-generator';
import { generateDockerfile } from './dockerfile-generator';
import { EDOT_VERSIONS, EDOT_COLLECTOR_IMAGE } from './versions';

interface BundleFile {
  path: string;
  content: string;
}

interface ConfigBundle {
  files: BundleFile[];
  readme: string;
}

/**
 * Generate README.md content for the bundle
 */
function generateReadme(
  nodes: Node<EDOTNodeData>[],
  deploymentModel: DeploymentModel,
  hasK8s: boolean,
  hasDocker: boolean
): string {
  const collectorNodes = nodes.filter(
    (n) => n.data.componentType === 'collector-agent' || n.data.componentType === 'collector-gateway'
  );
  const sdkNodes = nodes.filter((n) => n.data.componentType === 'edot-sdk') as Node<SDKNodeData>[];
  
  const deploymentInfo = {
    serverless: {
      name: 'Elastic Cloud Serverless',
      endpoint: 'Your Serverless project OTLP endpoint',
    },
    ech: {
      name: 'Elastic Cloud Hosted',
      endpoint: 'Your ECH deployment OTLP endpoint',
    },
    'self-managed': {
      name: 'Self-Managed Elasticsearch',
      endpoint: 'Your Elasticsearch cluster endpoint',
    },
  }[deploymentModel];

  let readme = `# EDOT Configuration Bundle

Generated by EDOT Flow Visualizer

## Overview

This bundle contains a fully runnable project to deploy your OpenTelemetry infrastructure with Elastic's Distribution of OpenTelemetry (EDOT).

**Deployment Model:** ${deploymentInfo.name}
**EDOT Collector Image:** \`${EDOT_COLLECTOR_IMAGE}\`

### Architecture Summary

`;

  // Add architecture description
  if (sdkNodes.length > 0) {
    readme += `- **${sdkNodes.length} Application(s):** `;
    readme += sdkNodes.map((n) => `${n.data.serviceName || n.data.label} (${n.data.language})`).join(', ');
    readme += '\n';
  }
  
  const agents = collectorNodes.filter((n) => n.data.componentType === 'collector-agent');
  const gateways = collectorNodes.filter((n) => n.data.componentType === 'collector-gateway');
  
  if (agents.length > 0) {
    readme += `- **${agents.length} Collector Agent(s):** Per-host/sidecar telemetry collection\n`;
  }
  if (gateways.length > 0) {
    readme += `- **${gateways.length} Collector Gateway(s):** Centralized processing and routing\n`;
  }

  readme += `
## Bundle Contents

\`\`\`
`;

  if (sdkNodes.length > 0) {
    readme += `apps/\n`;
    for (const sdk of sdkNodes) {
      const name = toFileName(sdk.data.serviceName || sdk.data.label);
      readme += `  ├── ${name}/\n`;
      readme += `  │   ├── Dockerfile              # EDOT-instrumented container\n`;
      readme += `  │   └── (app source files)       # Sample ${sdk.data.language} application\n`;
    }
  }

  if (collectorNodes.length > 0) {
    readme += `configs/\n`;
    for (const collector of collectorNodes) {
      const fileName = toFileName(collector.data.label);
      readme += `  ├── ${fileName}-config.yaml    # ${collector.data.componentType === 'collector-gateway' ? 'Gateway' : 'Agent'} configuration\n`;
    }
  }

  if (hasDocker) {
    readme += `docker-compose.yml              # Docker Compose for local deployment\n`;
  }

  if (hasK8s) {
    readme += `kubernetes/\n`;
    readme += `  ├── manifests.yaml              # K8s DaemonSet/Deployment manifests\n`;
  }

  readme += `.env.example                      # Environment variables template
Makefile                          # Convenience targets (up, down, logs)
README.md                         # This file
docs/
  └── architecture.md             # Architecture documentation
\`\`\`

## Quick Start

### Prerequisites

1. Elastic Observability deployment (Serverless, Cloud Hosted, or Self-Managed)
2. Docker and Docker Compose (for local testing)
3. kubectl configured (for Kubernetes deployment)

### Step 1: Configure Environment Variables

Copy the example environment file and fill in your values:

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` with your Elastic credentials:

\`\`\`bash
# Required
ELASTIC_APM_SERVER_URL=https://your-deployment.apm.elastic-cloud.com:443
ELASTIC_APM_SECRET_TOKEN=your-secret-token

# Optional
DEPLOYMENT_ENVIRONMENT=production
\`\`\`

`;

  if (hasDocker) {
    readme += `### Step 2: Deploy with Docker Compose

\`\`\`bash
# Load environment variables
source .env

# Build and start all services
make up

# Or manually:
docker-compose up -d --build

# View logs
make logs

# Stop services
make down
\`\`\`

`;

    // Add per-app access info
    if (sdkNodes.length > 0) {
      readme += `### Application Endpoints

| Service | URL | Language | EDOT SDK |
|---------|-----|----------|----------|
`;
      let port = 8080;
      for (const sdk of sdkNodes) {
        const edotSdk = getEdotSdkName(sdk.data.language);
        readme += `| ${sdk.data.serviceName || sdk.data.label} | http://localhost:${port} | ${sdk.data.language} | ${edotSdk} |\n`;
        port++;
      }
      readme += '\n';
    }
  }

  if (hasK8s) {
    readme += `### Step 2: Deploy to Kubernetes

\`\`\`bash
# Create namespace
kubectl create namespace observability

# Create secret with credentials
kubectl create secret generic elastic-apm \\
  --from-literal=server-url="\${ELASTIC_APM_SERVER_URL}" \\
  --from-literal=secret-token="\${ELASTIC_APM_SECRET_TOKEN}" \\
  -n observability

# Apply manifests
kubectl apply -f kubernetes/manifests.yaml

# Verify deployment
kubectl get pods -n observability
\`\`\`

`;
  }

  readme += `## EDOT Components Used

This project uses **Elastic's Distribution of OpenTelemetry (EDOT)**, not upstream OpenTelemetry packages.

| Component | EDOT Package | Version |
|-----------|-------------|---------|
| Collector | \`${EDOT_COLLECTOR_IMAGE}\` | ${EDOT_VERSIONS.collector} |
`;

  if (sdkNodes.some((n) => n.data.language === 'nodejs')) {
    readme += `| Node.js SDK | \`${EDOT_VERSIONS.nodePackage}\` | latest |\n`;
  }
  if (sdkNodes.some((n) => n.data.language === 'python')) {
    readme += `| Python SDK | \`${EDOT_VERSIONS.pythonPackage}\` | latest |\n`;
  }
  if (sdkNodes.some((n) => n.data.language === 'java')) {
    readme += `| Java Agent | \`co.elastic.otel:elastic-otel-javaagent\` | ${EDOT_VERSIONS.javaAgent} |\n`;
  }
  if (sdkNodes.some((n) => n.data.language === 'dotnet')) {
    readme += `| .NET SDK | \`${EDOT_VERSIONS.dotnetPackage}\` | latest |\n`;
  }

  readme += `
## Documentation

- [EDOT Documentation](https://www.elastic.co/docs/reference/opentelemetry)
- [EDOT Collector Configuration](https://www.elastic.co/docs/reference/edot-collector)
- [OpenTelemetry Documentation](https://opentelemetry.io/docs/)

## Support

For issues and questions:
- [Elastic Discuss Forums](https://discuss.elastic.co/)
- [GitHub Issues](https://github.com/elastic/opentelemetry/issues)

---

*Generated by [EDOT Flow Visualizer](https://github.com/elastic/opentelemetry)*
`;

  return readme;
}

/**
 * Generate .env.example content
 */
function generateEnvExample(deploymentModel: DeploymentModel): string {
  let content = `# EDOT Configuration Environment Variables
# Copy this file to .env and fill in your values

# ============================================
# Elastic Observability Credentials
# ============================================

`;

  if (deploymentModel === 'self-managed') {
    content += `# Elasticsearch endpoint (self-managed)
ELASTICSEARCH_ENDPOINT=https://your-elasticsearch:9200
ELASTICSEARCH_API_KEY=your-api-key

# For local development with Docker
ELASTIC_PASSWORD=changeme
KIBANA_PASSWORD=changeme
`;
  } else {
    content += `# Elastic Cloud endpoint
ELASTIC_APM_SERVER_URL=https://your-deployment.apm.elastic-cloud.com:443
ELASTIC_APM_SECRET_TOKEN=your-secret-token
`;
  }

  content += `
# ============================================
# Collector Configuration
# ============================================

# Storage directory for persistent state
STORAGE_DIR=/var/lib/otelcol

# Deployment environment name
DEPLOYMENT_ENVIRONMENT=production

# Gateway endpoint (for agent -> gateway forwarding)
GATEWAY_ENDPOINT=gateway:4317

# ============================================
# Optional Settings
# ============================================

# Log level (debug, info, warn, error)
OTEL_LOG_LEVEL=info

# Memory limit for collectors (MiB)
MEMORY_LIMIT_MIB=512
`;

  return content;
}

/**
 * Generate Makefile with convenience targets
 */
function generateMakefile(): string {
  return `.PHONY: up down logs build clean restart status

# Start all services
up:
\tdocker-compose up -d --build

# Stop all services
down:
\tdocker-compose down

# View logs (follow mode)
logs:
\tdocker-compose logs -f

# Build all images without starting
build:
\tdocker-compose build

# Stop and remove all containers, networks, and volumes
clean:
\tdocker-compose down -v --remove-orphans

# Restart all services
restart:
\tdocker-compose down && docker-compose up -d --build

# Show service status
status:
\tdocker-compose ps

# Show service health
health:
\t@echo "Checking service health..."
\t@docker-compose ps --format "table {{.Name}}\\t{{.Status}}"
`;
}

/**
 * Generate architecture documentation
 */
function generateArchitectureDocs(
  nodes: Node<EDOTNodeData>[],
  edges: Edge<FlowEdgeData>[],
  deploymentModel: DeploymentModel
): string {
  const sdkNodes = nodes.filter((n) => n.data.componentType === 'edot-sdk') as Node<SDKNodeData>[];
  const agentNodes = nodes.filter((n) => n.data.componentType === 'collector-agent');
  const gatewayNodes = nodes.filter((n) => n.data.componentType === 'collector-gateway');

  let doc = `# Architecture Documentation

## Deployment Model: ${deploymentModel === 'serverless' ? 'Elastic Cloud Serverless' : deploymentModel === 'ech' ? 'Elastic Cloud Hosted' : 'Self-Managed'}

## EDOT Components

All components use Elastic's Distribution of OpenTelemetry (EDOT):
- **Collector:** \`${EDOT_COLLECTOR_IMAGE}\`
- **Run command:** \`elastic-agent otel --config otel.yml\`

## Data Flow

\`\`\`
`;

  // Build a simple ASCII diagram
  if (sdkNodes.length > 0) {
    doc += `┌─────────────────────────────────────┐\n`;
    doc += `│           Applications              │\n`;
    doc += `│  ${sdkNodes.map((n) => n.data.serviceName || n.data.label).join(', ').substring(0, 30)}  │\n`;
    doc += `└────────────────┬────────────────────┘\n`;
    doc += `                 │ OTLP\n`;
    doc += `                 ▼\n`;
  }

  if (agentNodes.length > 0) {
    doc += `┌─────────────────────────────────────┐\n`;
    doc += `│      Collector Agent(s)             │\n`;
    doc += `│  Per-host collection & forwarding  │\n`;
    doc += `└────────────────┬────────────────────┘\n`;
    doc += `                 │ OTLP\n`;
    doc += `                 ▼\n`;
  }

  if (gatewayNodes.length > 0) {
    doc += `┌─────────────────────────────────────┐\n`;
    doc += `│      Collector Gateway              │\n`;
    doc += `│  Sampling, routing, aggregation    │\n`;
    doc += `└────────────────┬────────────────────┘\n`;
    doc += `                 │ OTLP/ES\n`;
    doc += `                 ▼\n`;
  }

  doc += `┌─────────────────────────────────────┐\n`;
  doc += `│      Elastic Observability          │\n`;
  doc += `│  APM, Logs, Metrics, Profiling      │\n`;
  doc += `└─────────────────────────────────────┘\n`;

  doc += `\`\`\`

## Component Details

`;

  // SDK details
  if (sdkNodes.length > 0) {
    doc += `### Applications (${sdkNodes.length})

| Service | Language | EDOT SDK | Auto-Instrumented |
|---------|----------|----------|-------------------|
`;
    for (const sdk of sdkNodes) {
      const edotSdk = getEdotSdkName(sdk.data.language);
      doc += `| ${sdk.data.serviceName || sdk.data.label} | ${sdk.data.language} | ${edotSdk} | ${sdk.data.autoInstrumented ? 'Yes' : 'No'} |\n`;
    }
    doc += '\n';
  }

  doc += `## Protocols

| Protocol | Port | Description |
|----------|------|-------------|
| OTLP/gRPC | 4317 | High-performance binary protocol |
| OTLP/HTTP | 4318 | HTTP-based, firewall-friendly |

## Environment Variables

See \`.env.example\` for required configuration.

## Monitoring

The collectors expose metrics on port 8888:

\`\`\`bash
curl http://localhost:8888/metrics
\`\`\`

Key metrics to watch:
- \`otelcol_receiver_accepted_spans\`
- \`otelcol_exporter_sent_spans\`
- \`otelcol_processor_dropped_spans\`
`;

  return doc;
}

/**
 * Convert label to file-safe name
 */
function toFileName(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'config';
}

/**
 * Get EDOT SDK name for a language
 */
function getEdotSdkName(language: string): string {
  switch (language) {
    case 'nodejs': return EDOT_VERSIONS.nodePackage;
    case 'python': return EDOT_VERSIONS.pythonPackage;
    case 'java': return `elastic-otel-javaagent:${EDOT_VERSIONS.javaAgent}`;
    case 'dotnet': return EDOT_VERSIONS.dotnetPackage;
    default: return 'upstream OTel SDK';
  }
}

/**
 * Generate all bundle files
 */
function generateBundleFiles(
  nodes: Node<EDOTNodeData>[],
  edges: Edge<FlowEdgeData>[],
  deploymentModel: DeploymentModel
): BundleFile[] {
  const files: BundleFile[] = [];

  // Get collector nodes
  const collectorNodes = nodes.filter(
    (n) => n.data.componentType === 'collector-agent' || n.data.componentType === 'collector-gateway'
  ) as Node<CollectorNodeData>[];

  // Get SDK nodes
  const sdkNodes = nodes.filter(
    (n) => n.data.componentType === 'edot-sdk'
  ) as Node<SDKNodeData>[];

  // Generate collector configs
  for (const collector of collectorNodes) {
    const fileName = toFileName(collector.data.label);
    const yaml = generateCollectorYAML(collector.data, { deploymentModel });
    files.push({
      path: `configs/${fileName}-config.yaml`,
      content: yaml,
    });
  }

  // Generate sample app source code and Dockerfiles for each SDK
  for (const sdk of sdkNodes) {
    const appName = toFileName(sdk.data.serviceName || sdk.data.label);
    
    // Generate Dockerfile
    const dockerfile = generateDockerfile(sdk.data.language, sdk.data.serviceName || sdk.data.label);
    files.push({
      path: `apps/${appName}/Dockerfile`,
      content: dockerfile,
    });

    // Generate sample app source files
    const appFiles = generateSampleApp(sdk.data);
    for (const [filename, content] of appFiles) {
      files.push({
        path: `apps/${appName}/${filename}`,
        content,
      });
    }
  }

  // Check for infrastructure nodes
  const hasDocker = nodes.some((n) => n.type === 'infrastructureDocker') || 
                    nodes.some((n) => n.data.componentType === 'edot-sdk' || 
                                       n.data.componentType === 'collector-agent' ||
                                       n.data.componentType === 'collector-gateway');
  const hasK8s = nodes.some(
    (n) =>
      n.type === 'infrastructureK8sNamespace' ||
      n.type === 'infrastructureK8sDaemonSet' ||
      n.type === 'infrastructureK8sDeployment'
  ) || (collectorNodes.length > 0 || sdkNodes.length > 0);

  // Generate Docker Compose
  if (hasDocker) {
    const dockerCompose = generateDockerCompose(nodes, edges, deploymentModel);
    files.push({
      path: 'docker-compose.yml',
      content: dockerCompose,
    });
  }

  // Generate K8s manifests
  if (hasK8s) {
    const k8sManifests = generateK8sManifests(nodes, edges, { deploymentModel });
    files.push({
      path: 'kubernetes/manifests.yaml',
      content: k8sManifests,
    });
  }

  // Generate README
  const readme = generateReadme(nodes, deploymentModel, hasK8s, hasDocker);
  files.push({
    path: 'README.md',
    content: readme,
  });

  // Generate .env.example
  const envExample = generateEnvExample(deploymentModel);
  files.push({
    path: '.env.example',
    content: envExample,
  });

  // Generate Makefile
  if (hasDocker) {
    files.push({
      path: 'Makefile',
      content: generateMakefile(),
    });
  }

  // Generate architecture docs
  const archDocs = generateArchitectureDocs(nodes, edges, deploymentModel);
  files.push({
    path: 'docs/architecture.md',
    content: archDocs,
  });

  return files;
}

/**
 * Generate a ZIP bundle containing all configuration files
 */
export async function generateConfigBundle(
  nodes: Node<EDOTNodeData>[],
  edges: Edge<FlowEdgeData>[],
  deploymentModel: DeploymentModel
): Promise<Blob> {
  const zip = new JSZip();
  
  // Generate all files
  const files = generateBundleFiles(nodes, edges, deploymentModel);
  
  // Add files to ZIP
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  
  // Generate ZIP blob
  return zip.generateAsync({ 
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

/**
 * Download the config bundle as a ZIP file
 */
export async function downloadConfigBundle(
  nodes: Node<EDOTNodeData>[],
  edges: Edge<FlowEdgeData>[],
  deploymentModel: DeploymentModel
): Promise<void> {
  const blob = await generateConfigBundle(nodes, edges, deploymentModel);
  
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'edot-config-bundle.zip';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Get a preview of what files will be in the bundle
 */
export function previewBundleContents(
  nodes: Node<EDOTNodeData>[],
  edges: Edge<FlowEdgeData>[],
  deploymentModel: DeploymentModel
): { path: string; size: number }[] {
  const files = generateBundleFiles(nodes, edges, deploymentModel);
  return files.map((f) => ({
    path: f.path,
    size: new Blob([f.content]).size,
  }));
}
