import type { Node } from '@xyflow/react';
import type {
  EDOTNodeData,
  K8sNamespaceNodeData,
  K8sDaemonSetNodeData,
  K8sDeploymentNodeData,
  CollectorNodeData,
} from '../types';

/**
 * Generates Kubernetes manifests from the current topology
 */
export function generateK8sManifests(nodes: Node<EDOTNodeData>[]): string {
  const namespaceNodes = nodes.filter(
    (node) => node.type === 'infrastructureK8sNamespace'
  ) as Node<K8sNamespaceNodeData>[];

  if (namespaceNodes.length === 0) {
    return `# No Kubernetes resources found in topology
# Add K8s Namespace, DaemonSet, or Deployment nodes from the Infrastructure section
`;
  }

  const manifests: string[] = [];

  // Process each namespace
  for (const nsNode of namespaceNodes) {
    const nsData = nsNode.data;

    // Generate Namespace manifest
    manifests.push(generateNamespace(nsData));

    // Find DaemonSets in this namespace
    const daemonSets = nodes.filter(
      (n) => n.parentId === nsNode.id && n.type === 'infrastructureK8sDaemonSet'
    ) as Node<K8sDaemonSetNodeData>[];

    for (const dsNode of daemonSets) {
      const children = nodes.filter((n) => n.parentId === dsNode.id);
      const collectorChild = children.find((c) => c.type === 'collector') as
        | Node<CollectorNodeData>
        | undefined;

      if (collectorChild) {
        manifests.push(generateDaemonSet(dsNode.data, collectorChild.data));
      }
    }

    // Find Deployments in this namespace
    const deployments = nodes.filter(
      (n) => n.parentId === nsNode.id && n.type === 'infrastructureK8sDeployment'
    ) as Node<K8sDeploymentNodeData>[];

    for (const deployNode of deployments) {
      const children = nodes.filter((n) => n.parentId === deployNode.id);
      const collectorChild = children.find((c) => c.type === 'collector') as
        | Node<CollectorNodeData>
        | undefined;

      if (collectorChild) {
        manifests.push(
          generateDeployment(deployNode.data, collectorChild.data)
        );
        manifests.push(generateService(deployNode.data));
      }
    }

    // Generate ConfigMap for collector configuration
    manifests.push(generateConfigMap(nsData.name));
  }

  // Add usage instructions at the top
  const header = `# Kubernetes Manifests for EDOT Infrastructure
# Generated by EDOT Flow Visualizer
# https://github.com/elastic/opentelemetry

# Prerequisites:
# 1. Set up Elastic Observability deployment
# 2. Create secret with APM credentials:
#    kubectl create secret generic elastic-apm \\
#      --from-literal=server-url='https://your-deployment.apm.elastic-cloud.com:443' \\
#      --from-literal=secret-token='your-secret-token' \\
#      -n observability

# Apply manifests:
# kubectl apply -f k8s-manifests.yaml

---
`;

  return header + manifests.join('\n---\n');
}

function generateNamespace(data: K8sNamespaceNodeData): string {
  const labels = data.labels || {};
  const labelLines = Object.entries(labels)
    .map(([k, v]) => `    ${k}: "${v}"`)
    .join('\n');

  return `apiVersion: v1
kind: Namespace
metadata:
  name: ${data.name}${
    labelLines
      ? `
  labels:
${labelLines}`
      : ''
  }`;
}

function generateDaemonSet(
  data: K8sDaemonSetNodeData,
  collector: CollectorNodeData
): string {
  const nodeSelector = data.nodeSelector || {};
  const nodeSelectorLines = Object.entries(nodeSelector)
    .map(([k, v]) => `    ${k}: "${v}"`)
    .join('\n');

  return `apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ${data.name}
  namespace: ${data.namespace}
  labels:
    app: edot-collector
    component: agent
spec:
  selector:
    matchLabels:
      app: edot-collector
      component: agent
  template:
    metadata:
      labels:
        app: edot-collector
        component: agent
    spec:${
      nodeSelectorLines
        ? `
      nodeSelector:
${nodeSelectorLines}`
        : ''
    }
      containers:
      - name: edot-collector
        image: docker.elastic.co/beats/elastic-agent:8.11.0
        env:
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: elastic-apm
              key: server-url
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: elastic-apm
              key: secret-token
        ports:
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 8888
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 200m
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: edot-collector-config
      serviceAccountName: edot-collector`;
}

function generateDeployment(
  data: K8sDeploymentNodeData,
  collector: CollectorNodeData
): string {
  const resources = data.resources || { cpu: '500m', memory: '1Gi' };

  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${data.name}
  namespace: ${data.namespace}
  labels:
    app: edot-collector
    component: gateway
spec:
  replicas: ${data.replicas}
  selector:
    matchLabels:
      app: edot-collector
      component: gateway
  template:
    metadata:
      labels:
        app: edot-collector
        component: gateway
    spec:
      containers:
      - name: edot-collector
        image: docker.elastic.co/beats/elastic-agent:8.11.0
        env:
        - name: ELASTIC_APM_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: elastic-apm
              key: server-url
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: elastic-apm
              key: secret-token
        ports:
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 8888
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: ${resources.memory}
            cpu: ${resources.cpu}
          requests:
            memory: ${resources.memory}
            cpu: ${resources.cpu}
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: edot-collector-config
      serviceAccountName: edot-collector`;
}

function generateService(data: K8sDeploymentNodeData): string {
  return `apiVersion: v1
kind: Service
metadata:
  name: ${data.name}
  namespace: ${data.namespace}
  labels:
    app: edot-collector
    component: gateway
spec:
  type: ClusterIP
  selector:
    app: edot-collector
    component: gateway
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    protocol: TCP`;
}

function generateConfigMap(namespace: string): string {
  return `apiVersion: v1
kind: ConfigMap
metadata:
  name: edot-collector-config
  namespace: ${namespace}
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
          disk:
          network:

    processors:
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 5s
      batch:
        timeout: 10s
        send_batch_size: 1024

    exporters:
      elasticsearch:
        endpoint: \${ELASTIC_APM_SERVER_URL}
        headers:
          Authorization: "Bearer \${ELASTIC_APM_SECRET_TOKEN}"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch]
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edot-collector
  namespace: ${namespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edot-collector
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "namespaces", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edot-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edot-collector
subjects:
- kind: ServiceAccount
  name: edot-collector
  namespace: ${namespace}`;
}

/**
 * Downloads the k8s-manifests.yaml file
 */
export function downloadK8sManifests(content: string) {
  const blob = new Blob([content], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'k8s-manifests.yaml';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
